name: Question
description: Ask us almost anything
labels: [question]
body:
- type: markdown
  attributes:
    value: |
      Before we begin, please confirm your question is not already [answered](https://github.com/Tsuey/L4D2-Community-Update/issues?q=label%3Aquestion). Also, your question may already be addressed in our [Code of Conduct](https://github.com/Tsuey/L4D2-Community-Update/blob/main/CODE_OF_CONDUCT.md) or [Contributing Guidelines](https://github.com/Tsuey/L4D2-Community-Update/blob/main/CONTRIBUTING.md).

      Tip: You can upload images by simply pasting them in.
- type: textarea
  attributes:
    label: Question
    description: What is on your mind?
  validations:
    required: true